In [ ]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.6.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.6
ale-py                                0.11.0
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.21.0
astropy                               7.0.2
astropy-iers-data                     0.2025.5.12.0.38.29
astunparse                            1.6.3
atpublic                              5.1
attrs                                 25.3.0
audioread                             3.0.1
autograd                              1.8.0
babel                                 2.17.0
backcall                              0.2.0
backports.tarfile                     1.2.0
beautifulsoup4                        4.13.4
betterproto                           2.0.0b6
bigframes                             2.4.0
bigquery-magics                       0.9.0
bleach                                6.2.0
blinker                               1.9.0
blis                                  1.3.0
blobfile                              3.0.0
blosc2                                3.3.2
bokeh                                 3.7.3
Bottleneck                            1.4.2
bqplot                                0.12.44
branca                                0.8.1
build                                 1.2.2.post1
CacheControl                          0.14.3
cachetools                            5.5.2
catalogue                             2.0.10
certifi                               2025.4.26
cffi                                  1.17.1
chardet                               5.2.0
charset-normalizer                    3.4.2
chex                                  0.1.89
clarabel                              0.10.0
click                                 8.2.0
cloudpathlib                          0.21.0
cloudpickle                           3.1.1
cmake                                 3.31.6
cmdstanpy                             1.2.5
colorcet                              3.1.0
colorlover                            0.3.0
colour                                0.1.5
community                             1.0.0b1
confection                            0.1.5
cons                                  0.4.6
contourpy                             1.3.2
cramjam                               2.10.0
cryptography                          43.0.3
cuda-python                           12.6.2.post1
cudf-cu12                             25.2.1
cudf-polars-cu12                      25.2.2
cufflinks                             0.17.3
cuml-cu12                             25.2.1
cupy-cuda12x                          13.3.0
curl_cffi                             0.10.0
cuvs-cu12                             25.2.1
cvxopt                                1.3.2
cvxpy                                 1.6.5
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.11
Cython                                3.0.12
dask                                  2024.12.1
dask-cuda                             25.2.0
dask-cudf-cu12                        25.2.2
dask-expr                             1.1.21
dataproc-spark-connect                0.7.3
datascience                           0.17.6
datasets                              2.14.4
db-dtypes                             1.4.3
dbus-python                           1.2.18
debugpy                               1.8.0
decorator                             4.4.2
defusedxml                            0.7.1
diffusers                             0.33.1
dill                                  0.3.7
distributed                           2024.12.1
distributed-ucxx-cu12                 0.42.0
distro                                1.9.0
dlib                                  19.24.6
dm-tree                               0.1.9
docker-pycreds                        0.4.0
docstring_parser                      0.16
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.2.2
earthengine-api                       1.5.15
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.2
einops                                0.8.1
en_core_web_sm                        3.8.0
entrypoints                           0.4
et_xmlfile                            2.0.0
etils                                 1.12.2
etuples                               0.3.9
Farama-Notifications                  0.0.4
fastai                                2.7.19
fastcore                              1.7.29
fastdownload                          0.0.7
fastjsonschema                        2.21.1
fastprogress                          1.0.3
fastrlock                             0.8.3
filelock                              3.18.0
firebase-admin                        6.8.0
Flask                                 3.1.1
flatbuffers                           25.2.10
flax                                  0.10.6
folium                                0.19.5
fonttools                             4.58.0
frozendict                            2.4.6
frozenlist                            1.6.0
fsspec                                2025.3.2
future                                1.0.0
gast                                  0.6.0
gcsfs                                 2025.3.2
GDAL                                  3.6.4
gdown                                 5.2.0
geemap                                0.35.3
geocoder                              1.38.1
geographiclib                         2.0
geopandas                             1.0.1
geopy                                 2.4.1
gin-config                            0.5.0
gitdb                                 4.0.12
GitPython                             3.1.44
glob2                                 0.7
google                                2.0.3
google-ai-generativelanguage          0.6.15
google-api-core                       2.24.2
google-api-python-client              2.169.0
google-auth                           2.38.0
google-auth-httplib2                  0.2.0
google-auth-oauthlib                  1.2.2
google-cloud-aiplatform               1.92.0
google-cloud-bigquery                 3.32.0
google-cloud-bigquery-connection      1.18.2
google-cloud-bigquery-storage         2.31.0
google-cloud-core                     2.4.3
google-cloud-dataproc                 5.18.1
google-cloud-datastore                2.21.0
google-cloud-firestore                2.20.2
google-cloud-functions                1.20.3
google-cloud-iam                      2.19.0
google-cloud-language                 2.17.1
google-cloud-resource-manager         1.14.2
google-cloud-spanner                  3.54.0
google-cloud-storage                  2.19.0
google-cloud-translate                3.20.2
google-colab                          1.0.0
google-crc32c                         1.7.1
google-genai                          1.15.0
google-generativeai                   0.8.5
google-pasta                          0.2.0
google-resumable-media                2.7.2
googleapis-common-protos              1.70.0
googledrivedownloader                 1.1.0
graphviz                              0.20.3
greenlet                              3.2.2
grpc-google-iam-v1                    0.14.2
grpc-interceptor                      0.15.4
grpcio                                1.71.0
grpcio-status                         1.71.0
grpclib                               0.4.8
gspread                               6.2.0
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.0.8
gymnasium                             1.1.1
h11                                   0.16.0
h2                                    4.2.0
h5netcdf                              1.6.1
h5py                                  3.13.0
hdbscan                               0.8.40
hf_transfer                           0.1.9
highspy                               1.10.0
holidays                              0.72
holoviews                             1.20.2
hpack                                 4.1.0
html5lib                              1.1
httpcore                              1.0.9
httpimport                            1.4.1
httplib2                              0.22.0
httpx                                 0.28.1
huggingface-hub                       0.31.2
humanize                              4.12.3
hyperframe                            6.1.0
hyperopt                              0.2.7
ibis-framework                        9.5.0
idna                                  3.10
imageio                               2.37.0
imageio-ffmpeg                        0.6.0
imagesize                             1.4.1
imbalanced-learn                      0.13.0
immutabledict                         4.2.1
importlib_metadata                    8.7.0
importlib_resources                   6.5.2
imutils                               0.5.4
inflect                               7.5.0
iniconfig                             2.1.0
intel-cmplr-lib-ur                    2025.1.1
intel-openmp                          2025.1.1
ipyevents                             2.0.2
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.19.2
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipytree                               0.2.2
ipywidgets                            7.7.1
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.0.1
jaraco.functools                      4.1.0
jax                                   0.5.2
jax-cuda12-pjrt                       0.5.1
jax-cuda12-plugin                     0.5.1
jaxlib                                0.5.1
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.9.0
joblib                                1.5.0
jsonpatch                             1.33
jsonpickle                            4.0.5
jsonpointer                           3.0.0
jsonschema                            4.23.0
jsonschema-specifications             2025.4.1
jupyter-client                        6.1.12
jupyter-console                       6.1.0
jupyter_core                          5.7.2
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.19.2
jupyter-server                        1.16.0
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.15
kaggle                                1.7.4.5
kagglehub                             0.3.12
keras                                 3.8.0
keras-hub                             0.18.1
keras-nlp                             0.18.1
keyring                               25.6.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.4.8
langchain                             0.3.25
langchain-core                        0.3.59
langchain-text-splitters              0.3.8
langcodes                             3.5.0
langsmith                             0.3.42
language_data                         1.3.0
launchpadlib                          1.10.16
lazr.restfulclient                    0.14.4
lazr.uri                              1.0.6
lazy_loader                           0.4
libclang                              18.1.1
libcudf-cu12                          25.2.1
libcugraph-cu12                       25.2.0
libcuml-cu12                          25.2.1
libcuvs-cu12                          25.2.1
libkvikio-cu12                        25.2.1
libpysal                              4.13.0
libraft-cu12                          25.2.0
librosa                               0.11.0
libucx-cu12                           1.18.1
libucxx-cu12                          0.42.0
lightgbm                              4.5.0
linkify-it-py                         2.0.3
llvmlite                              0.43.0
locket                                1.0.0
logical-unification                   0.4.6
lxml                                  5.4.0
Mako                                  1.1.3
marisa-trie                           1.2.1
Markdown                              3.8
markdown-it-py                        3.0.0
MarkupSafe                            3.0.2
matplotlib                            3.10.0
matplotlib-inline                     0.1.7
matplotlib-venn                       1.1.2
mdit-py-plugins                       0.4.2
mdurl                                 0.1.2
miniKanren                            1.0.3
missingno                             0.5.2
mistune                               3.1.3
mizani                                0.13.5
mkl                                   2025.0.1
ml-dtypes                             0.4.1
mlxtend                               0.23.4
more-itertools                        10.7.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.1.0
multidict                             6.4.3
multipledispatch                      1.0.0
multiprocess                          0.70.15
multitasking                          0.0.11
murmurhash                            1.0.12
music21                               9.3.0
namex                                 0.0.9
narwhals                              1.39.0
natsort                               8.4.0
nbclassic                             1.3.1
nbclient                              0.10.2
nbconvert                             7.16.6
nbformat                              5.10.4
ndindex                               1.9.2
nest-asyncio                          1.6.0
networkx                              3.4.2
nibabel                               5.3.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.60.0
numba-cuda                            0.2.0
numexpr                               2.10.2
numpy                                 2.0.2
nvidia-cublas-cu12                    12.5.3.2
nvidia-cuda-cupti-cu12                12.5.82
nvidia-cuda-nvcc-cu12                 12.5.82
nvidia-cuda-nvrtc-cu12                12.5.82
nvidia-cuda-runtime-cu12              12.5.82
nvidia-cudnn-cu12                     9.3.0.75
nvidia-cufft-cu12                     11.2.3.61
nvidia-curand-cu12                    10.3.6.82
nvidia-cusolver-cu12                  11.6.3.83
nvidia-cusparse-cu12                  12.5.1.3
nvidia-cusparselt-cu12                0.6.2
nvidia-ml-py                          12.575.51
nvidia-nccl-cu12                      2.21.5
nvidia-nvcomp-cu12                    4.2.0.11
nvidia-nvjitlink-cu12                 12.5.82
nvidia-nvtx-cu12                      12.4.127
nvtx                                  0.2.11
nx-cugraph-cu12                       25.2.0
oauth2client                          4.1.3
oauthlib                              3.2.2
omegaconf                             2.3.0
openai                                1.78.1
opencv-contrib-python                 4.11.0.86
opencv-python                         4.11.0.86
opencv-python-headless                4.11.0.86
openpyxl                              3.1.5
opt_einsum                            3.4.0
optax                                 0.2.4
optree                                0.15.0
orbax-checkpoint                      0.11.13
orjson                                3.10.18
osqp                                  1.0.4
packaging                             24.2
pandas                                2.2.2
pandas-datareader                     0.10.0
pandas-gbq                            0.28.1
pandas-stubs                          2.2.2.240909
pandocfilters                         1.5.1
panel                                 1.6.3
param                                 2.2.0
parso                                 0.8.4
parsy                                 2.1
partd                                 1.4.2
pathlib                               1.0.1
patsy                                 1.0.1
peewee                                3.18.1
peft                                  0.15.2
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.2.1
pip                                   24.1.2
platformdirs                          4.3.8
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.5.0
ply                                   3.11
polars                                1.21.0
pooch                                 1.8.2
portpicker                            1.5.2
preshed                               3.0.9
prettytable                           3.16.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.21.1
promise                               2.3
prompt_toolkit                        3.0.51
propcache                             0.3.1
prophet                               1.1.6
proto-plus                            1.26.1
protobuf                              5.29.4
psutil                                5.9.5
psycopg2                              2.9.10
ptyprocess                            0.7.0
py-cpuinfo                            9.0.0
py4j                                  0.10.9.7
pyarrow                               18.1.0
pyasn1                                0.6.1
pyasn1_modules                        0.4.2
pycairo                               1.28.0
pycocotools                           2.0.8
pycparser                             2.22
pycryptodomex                         3.22.0
pydantic                              2.11.4
pydantic_core                         2.33.2
pydata-google-auth                    1.9.1
pydot                                 3.0.4
pydotplus                             2.0.2
PyDrive                               1.3.1
PyDrive2                              1.21.3
pyerfa                                2.0.1.5
pygame                                2.6.1
pygit2                                1.18.0
Pygments                              2.19.1
PyGObject                             3.42.0
PyJWT                                 2.10.1
pylibcudf-cu12                        25.2.1
pylibcugraph-cu12                     25.2.0
pylibraft-cu12                        25.2.0
pymc                                  5.22.0
pymystem3                             0.2.0
pynndescent                           0.5.13
pynvjitlink-cu12                      0.6.0
pynvml                                12.0.0
pyogrio                               0.11.0
pyomo                                 6.9.2
PyOpenGL                              3.1.9
pyOpenSSL                             24.2.1
pyparsing                             3.2.3
pyperclip                             1.9.0
pyproj                                3.7.1
pyproject_hooks                       1.2.0

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
#Can be thought of as a dict-like container for Series objects

In [ ]:
# let's access total room
df["total_rooms"]

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [ ]:
# or we can do
df.total_bedrooms

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
# access 1st item in total bedrooms
df.total_bedrooms[0]

np.float64(661.0)

In [ ]:
df['total_bedrooms'][2999]

np.float64(263.0)

In [ ]:
# 1. https://huggingface.co/datasets/lukebarousse/data_jobs ----> file&versions ----> csv ---> dowload ---> upload to notebook
# 2. by load dataset function which allows to provide the name of our data set & load

In [ ]:
# 1 way to upload data file
#!pip install datasets
# from datasets import load_dataset
# dataset = load_dataset('lukebarousse/data_jobs')

#data_jobs file

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/data_jobs.csv")

<ipython-input-5-1cd17c9ff355>:1: DtypeWarning: Columns (5,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/data_jobs.csv")

#access different columns and rows

In [ ]:
#df.head(2)                  give me first 2 rows
#df.tail(4)                  give me last 4 rows
#df['job_title_short']        give me this spesific column
#df[['job_title_short','job_location']]        making list to provide multiple different column

In [ ]:
# to view 92 - 100 rows, we are using iloc method
#df.iloc[90:93,0:2]     from 90 - 93 rows print first 2 columns   or we can do
#df[['job_title_short','job_location']].iloc[90:100]

#methods

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35543 entries, 0 to 35542
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        35543 non-null  object
 1   job_title              35543 non-null  object
 2   job_location           35492 non-null  object
 3   job_via                35541 non-null  object
 4   job_schedule_type      34932 non-null  object
 5   job_work_from_home     35543 non-null  object
 6   search_location        35542 non-null  object
 7   job_posted_date        35542 non-null  object
 8   job_no_degree_mention  35542 non-null  object
 9   job_health_insurance   35542 non-null  object
 10  job_country            35538 non-null  object
 11  salary_rate            1422 non-null   object
 12  salary_year_avg        1025 non-null   float64
 13  salary_hour_avg        381 non-null    float64
 14  company_name           35541 non-null  object
 15  job_skills             30728 non-null  object
 16  job_type_skills        30728 non-null  object
dtypes: float64(2), object(15)
memory usage: 4.6+ MB

In [ ]:
len(df)

35543

In [ ]:
df.shape

(35543, 17)

In [ ]:
df.index

RangeIndex(start=0, stop=35543, step=1)

In [ ]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')

In [ ]:
df.count()

job_title_short          35543
job_title                35543
job_location             35492
job_via                  35541
job_schedule_type        34932
job_work_from_home       35543
search_location          35542
job_posted_date          35542
job_no_degree_mention    35542
job_health_insurance     35542
job_country              35538
salary_rate               1422
salary_year_avg           1025
salary_hour_avg            381
company_name             35541
job_skills               30728
job_type_skills          30728
dtype: int64

In [ ]:
df.describe()      # it'll discribe only neumerical column

       salary_year_avg  salary_hour_avg
count      1025.000000       381.000000
mean     126783.371772        50.113084
std       49325.274717        21.971638
min       30750.000000         8.500000
25%       90000.000000        31.500000
50%      120000.000000        50.889999
75%      151000.000000        65.000000
max      375000.000000       130.000000

In [ ]:
# to get only uniqe value in job title short
df.job_title_short.unique()       # or  df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [ ]:
# using comparison operator to specifically identify certain job titles
#df.job_title_short == 'Data Analyst'      it'll give me a boolean
df[df.job_title_short == 'Data Analyst']    # df will filter for this condition

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,NaN,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,NaN,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
31,Data Analyst,Stage - Data Analyst F/H,"Paris, France",via LinkedIn,Full-time and Internship,False,France,2023-10-19 13:59:31,False,False,France,NaN,NaN,NaN,GROUPE BON MARCHÉ : Le Bon Marché Rive Gauche ...,['sql'],{'programming': ['sql']}
34,Data Analyst,Data Analyst als Marketing Manager Automation ...,"Erlangen, Germany",via Central Illinois Proud Jobs,Full-time,False,Germany,2023-02-23 13:31:28,True,False,Germany,NaN,NaN,NaN,DEFACTO GmbH,['sap'],{'analyst_tools': ['sap']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35514,Data Analyst,Data Analyst,Anywhere,via Indeed,Full-time,True,United Kingdom,2023-03-22 13:29:38,True,False,United Kingdom,NaN,NaN,NaN,Inclusive Recruiting,['excel'],{'analyst_tools': ['excel']}
35517,Data Analyst,Data Analyst (w/m/d),"Wiesbaden, Germany",via StepStone,Full-time,False,Germany,2023-05-02 13:24:52,False,False,Germany,NaN,NaN,NaN,Statistisches Bundesamt,NaN,NaN
35531,Data Analyst,Entry-Level Compliance Data Analyst - Temp,"New York, NY",via Monster,NaN,False,"New York, United States",2023-04-05 12:59:52,False,True,United States,NaN,NaN,NaN,Infinity Consulting Solutions,['notion'],{'async': ['notion']}
35534,Data Analyst,Research Data Analyst,"Baltimore, MD",via Inside Higher Ed Careers,Full-time,False,"New York, United States",2023-06-03 13:00:03,False,True,United States,NaN,NaN,NaN,Johns Hopkins University,"['sas', 'sas', 'r', 'spss']","{'analyst_tools': ['sas', 'spss'], 'programmin..."
35537,Data Analyst,Data-Analyst - H/F,"Gevrey-Chambertin, France",via BeBee,Full-time,False,France,2023-08-20 13:41:23,False,False,France,NaN,NaN,NaN,ATOL CONSEILS ET DEVELOPPEMENTS,"['sql', 'qlik', 'tableau', 'power bi']","{'analyst_tools': ['qlik', 'tableau', 'power b..."

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df['salary_year_avg'] > 100000)]
# in here if we want any of these one want to be correct then use "or (|) " condition

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
1555,Data Analyst,Data Analyst/Engineer (M/F/D),"Aveiro, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-04-25 13:27:25,False,False,Portugal,year,111175.0,NaN,Bosch Group,"['databricks', 'spark']","{'cloud': ['databricks'], 'libraries': ['spark']}"
1681,Data Analyst,Data Analyst,"Irvine, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-03-23 13:01:14,False,True,United States,year,111175.0,NaN,Western Digital,"['sql', 'tableau', 'power bi', 'excel']","{'analyst_tools': ['tableau', 'power bi', 'exc..."
1684,Data Analyst,Data Analyst - Data17829,"Tampa, FL",via Indeed,Full-time,False,"Florida, United States",2023-07-18 13:02:09,True,True,United States,year,120000.0,NaN,Acrisure,"['shell', 'sql', 'azure', 'databricks', 'linux']","{'cloud': ['azure', 'databricks'], 'os': ['lin..."
1867,Data Analyst,Data Integration Analyst (West Coast/Chicago),"Chicago, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-07-18 13:01:47,False,False,United States,year,101500.0,NaN,Forsta,"['php', 'python', 'express']","{'programming': ['php', 'python'], 'webframewo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33182,Data Analyst,"Data Analyst, Field Reliability Group","Sunnyvale, CA",via Ladders,Full-time,False,"California, United States",2023-01-11 13:02:12,True,True,United States,year,115000.0,NaN,"Tesla, Inc",NaN,NaN
33362,Data Analyst,Data Analyst - Analyst12277,"Modesto, CA",via Indeed,Full-time,False,"California, United States",2023-07-27 13:00:50,True,True,United States,year,127500.0,NaN,Booz Allen Hamilton,"['shell', 'sql', 'linux']","{'os': ['linux'], 'programming': ['shell', 'sq..."
33899,Data Analyst,Sr. Data Analyst,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-09-19 13:01:02,True,True,United States,year,130000.0,NaN,Launch Consulting Group,"['sql', 'azure', 'aws', 'snowflake', 'visio', ...","{'analyst_tools': ['visio', 'excel', 'power bi..."
34607,Data Analyst,Data Analyst (ID#10252),"Oakland, CA",via Indeed,Full-time,False,"California, United States",2023-05-15 13:00:46,True,True,United States,year,110000.0,NaN,Worldgate LLC,"['sql', 'python', 'c#', 'powershell', 'sql ser...","{'analyst_tools': ['word', 'excel', 'outlook']..."
34647,Data Analyst,Data Analyst & Visualization Engineer,"Herndon, VA",via LifeworQ,Full-time,False,"New York, United States",2023-12-10 13:00:06,False,False,United States,year,145500.0,NaN,Peraton,"['splunk', 'tableau']","{'analyst_tools': ['splunk', 'tableau']}"

In [ ]:
# running data analyst job with which have salaries
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg.notna())] [['job_title_short','salary_year_avg']]

      job_title_short  salary_year_avg
109      Data Analyst          89000.0
180      Data Analyst          90250.0
410      Data Analyst         133285.0
988      Data Analyst          62623.0
1413     Data Analyst          71300.0
...               ...              ...
33926    Data Analyst          63579.0
34083    Data Analyst          75000.0
34473    Data Analyst          90000.0
34607    Data Analyst         110000.0
34647    Data Analyst         145500.0

[233 rows x 2 columns]